/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: entry.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "entry.pb-c.h"
void   entry__init
                     (Entry         *message)
{
  static const Entry init_value = ENTRY__INIT;
  *message = init_value;
}
size_t entry__get_packed_size
                     (const Entry *message)
{
  assert(message->base.descriptor == &entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t entry__pack
                     (const Entry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t entry__pack_to_buffer
                     (const Entry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Entry *
       entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Entry *)
     protobuf_c_message_unpack (&entry__descriptor,
                                allocator, len, data);
}
void   entry__free_unpacked
                     (Entry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor entry__field_descriptors[3] =
{
  {
    "volumes",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Entry, n_volumes),
    offsetof(Entry, volumes),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hash",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Entry, hash),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deleted",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Entry, deleted),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned entry__field_indices_by_name[] = {
  2,   /* field[2] = deleted */
  1,   /* field[1] = hash */
  0,   /* field[0] = volumes */
};
static const ProtobufCIntRange entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "entry",
  "Entry",
  "Entry",
  "",
  sizeof(Entry),
  3,
  entry__field_descriptors,
  entry__field_indices_by_name,
  1,  entry__number_ranges,
  (ProtobufCMessageInit) entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
